# Generated by Django 2.1.5 on 2019-10-30 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_omr_templates_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('ansKey', models.FileField(upload_to='')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='functions.omr_templates')),
            ],
        ),
    ]
