# Generated by Django 2.1.5 on 2019-10-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0004_exam_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='ansKeyMeta',
            field=models.FileField(default='NO_META', upload_to=''),
            preserve_default=False,
        ),
    ]
