# Generated by Django 2.1.5 on 2019-10-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0005_exam_anskeymeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='ansKey',
            field=models.FileField(upload_to='exams/answer_key/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='ansKeyMeta',
            field=models.FileField(upload_to='exams/answerkey_meta/'),
        ),
        migrations.AlterField(
            model_name='omr_templates',
            name='pdf',
            field=models.FileField(upload_to='templates/'),
        ),
    ]
