# Generated by Django 2.1.5 on 2019-11-01 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('functions', '0006_auto_20191031_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnserSheets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='temp_anssheet/')),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='functions.Exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
