# Generated by Django 2.1.5 on 2019-11-01 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('functions', '0007_ansersheets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnserSheets',
            new_name='AnswerSheets',
        ),
        migrations.AlterModelOptions(
            name='answersheets',
            options={'verbose_name_plural': 'AnswerSheets'},
        ),
    ]
