# Generated by Django 2.1.5 on 2019-11-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0008_auto_20191101_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersheets',
            name='Exam',
        ),
        migrations.RemoveField(
            model_name='answersheets',
            name='user',
        ),
        migrations.DeleteModel(
            name='AnswerSheets',
        ),
    ]
