# Generated by Django 2.1.5 on 2019-11-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0009_auto_20191101_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='ansKeyMeta',
        ),
    ]
