# Generated by Django 2.1.5 on 2019-11-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0010_remove_exam_anskeymeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='ansKeyImg',
            field=models.FileField(default='SDfsdf', upload_to='exams/answer_key_img/'),
            preserve_default=False,
        ),
    ]
