# Generated by Django 2.2.7 on 2019-11-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0011_exam_anskeyimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='ansKey',
            field=models.FileField(blank=True, null=True, upload_to='exams/answer_key/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='ansKeyImg',
            field=models.FileField(blank=True, null=True, upload_to='exams/answer_key_img/'),
        ),
    ]
