# Generated by Django 2.2.7 on 2019-11-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0013_auto_20191120_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='ansKey',
            field=models.FileField(default='add an ans key', upload_to='exams/answer_key/'),
            preserve_default=False,
        ),
    ]
