# Generated by Django 2.0.7 on 2019-11-24 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0014_auto_20191121_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
