# Generated by Django 2.1.5 on 2019-12-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0015_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='ansKey',
            field=models.FileField(blank=True, null=True, upload_to='exams/answer_key/'),
        ),
    ]
